<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Portfolio 1: Gamelytics: Mobile Game Analytics Challenge 1</title>

<script src="site_libs/header-attrs-2.31/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
<li>
  <a href="p10.html">Portfolio 10</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Portfolio 1: Gamelytics: Mobile Game
Analytics Challenge 1</h1>

</div>


<blockquote>
<p>Goal: For the first portfolio, the goal is to use some of the tools
we have learned in earlier modules and more to clean, summarize, and
visualize a Gamelytics dataset from Kaggle. I will also try to evaluate
whether a new promotional offer(the test group) improves user (player)
outcomes compared to the current offer (control group) using A/B testing
for the conversion rate and revenue per use, as suggested as part of the
Kaggle challenges for this dataset. For the purpose of this protfolio,
we are going to assume the revenue is in dollars as there is no
indication of currency in the description.</p>
</blockquote>
<p>Here is the link for the Kaggle Challenge: <a
href="https://www.kaggle.com/datasets/debs2x/gamelytics-mobile-analytics-challenge?select=ab_test.csv"
class="uri">https://www.kaggle.com/datasets/debs2x/gamelytics-mobile-analytics-challenge?select=ab_test.csv</a></p>
<p>#Will start by loading all the packages I may be using for this.</p>
<pre class="r"><code>library(tidyverse) 
library(tidyr)
library(ggplot2)</code></pre>
<p>#Import a/b test data (csv, separated by semicolon; used delim)</p>
<pre class="r"><code>library(readr)

ab_test &lt;- read_delim(
  &quot;data/ab_test.csv&quot;,
  delim = &quot;;&quot;,
  escape_double = FALSE,
  trim_ws = TRUE
)</code></pre>
<pre><code>## Rows: 404770 Columns: 3
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;;&quot;
## chr (1): testgroup
## dbl (2): user_id, revenue
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>View(ab_test)</code></pre>
<p>#Do a quick check/poke around the dataset.</p>
<pre class="r"><code>names(ab_test)  #checking if the file is read correctly</code></pre>
<pre><code>## [1] &quot;user_id&quot;   &quot;revenue&quot;   &quot;testgroup&quot;</code></pre>
<pre class="r"><code>glimpse(ab_test)</code></pre>
<pre><code>## Rows: 404,770
## Columns: 3
## $ user_id   &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…
## $ revenue   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ testgroup &lt;chr&gt; &quot;b&quot;, &quot;a&quot;, &quot;a&quot;, &quot;b&quot;, &quot;b&quot;, &quot;b&quot;, &quot;b&quot;, &quot;b&quot;, &quot;b&quot;, &quot;a&quot;, &quot;a&quot;, &quot;a&quot;, …</code></pre>
<p>Here is some quick guide to what each column is measuring:</p>
<p>user_id: A unique identifier for each user</p>
<p>revenue: The revenue generated by the user</p>
<p>testgroup: The group to which the user was assigned (object, e.g.,
“a” or “b”)</p>
<p>Quick check into the revenue data we have</p>
<pre class="r"><code>summary(ab_test$revenue)</code></pre>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
##     0.00     0.00     0.00    26.08     0.00 37433.00</code></pre>
<p>It looks like the data is very spread out. Let’s visualize this.</p>
<pre class="r"><code>ggplot(ab_test, aes(x = revenue)) + 
  geom_histogram() +
  labs (
    title = &quot;Distribution of Gamelytics Revenue&quot;,
    x = &quot;Revenue Generated by User ($)&quot;,
    y = &quot;Number of Users&quot;
  ) +
  theme_bw()</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
<p><img src="p01_files/figure-html/revenue-histogram-1.png" alt="" width="672" /></p>
<p>The data is heavily right-skewed. A lot of people did not pay
anything at all, while there is a very small number of people paying
about less than $10,000. We have also seen that the maximum amount spent
is a little under $40,000.</p>
<p>Next, I wanted to do a quick check into the test groups.</p>
<pre class="r"><code>ab_test %&gt;% count(testgroup)</code></pre>
<pre><code>## # A tibble: 2 × 2
##   testgroup      n
##   &lt;chr&gt;      &lt;int&gt;
## 1 a         202103
## 2 b         202667</code></pre>
<p>Looks like the number of people in the two groups are pretty
balanced, and we have a very large sample size for both groups.</p>
<p>Because there are only few people that have spent money, it’s not
very helpful to visualize if they’re mixed together with the majority of
the population which are non-payers. So, I am creating a new variable
that shows who paid.</p>
<pre class="r"><code>ab &lt;- ab_test %&gt;%
  mutate (payer_user = revenue &gt; 0)</code></pre>
<pre class="r"><code>ab %&gt;% count (payer_user)</code></pre>
<pre><code>## # A tibble: 2 × 2
##   payer_user      n
##   &lt;lgl&gt;       &lt;int&gt;
## 1 FALSE      401037
## 2 TRUE         3733</code></pre>
<pre class="r"><code>ab %&gt;%
  count(payer_user) %&gt;%
  ggplot(aes(x = payer_user, y = n, fill = payer_user)) + 
  geom_col() +
  labs (
    title = &quot;Gamelytics: Paying vs Non-Paying Users&quot;,
    x = &quot;Is the user paying?&quot;,
    y = &quot;Number of Users&quot;,
    fill = &quot;User is payer&quot;
  ) +
  theme_bw()</code></pre>
<p><img src="p01_files/figure-html/visualize-payer-nonpayer-1.png" alt="" width="672" /></p>
<div id="conversion-rates" class="section level3">
<h3>Conversion Rates</h3>
<p>Now that I have differentiated who is paying, I would like to take a
look at the conversion rate (percent of users who pay) in both
groups.</p>
<pre class="r"><code>conv_rate_by_group &lt;- ab %&gt;%
  group_by(testgroup) %&gt;%   #split the data into group a and b
  summarise(
    conversion_rate = mean(payer_user),  #what proportion paid in each group  
    n_users = n(),   #how many users in each group
    .groups = &quot;drop&quot;
  )</code></pre>
<p>We can see that there are 0.95% of paying users in test group ‘a’ and
0.89% paying users in test group ‘b’.</p>
<pre class="r"><code>ggplot (conv_rate_by_group,
        aes(x = testgroup,
            y = conversion_rate, 
            fill = testgroup)) + 
  geom_col() +
  scale_y_continuous(labels = scales::percent_format(accuracy = 0.01)) +
  scale_fill_manual(values = c(&quot;a&quot; = &quot;orange&quot;,
                               &quot;b&quot; = &quot;steelblue&quot;)) +
  labs (
    title = &quot;Conversion Rate by Test Group&quot;,
    x = &quot;Test Group&quot;,
    y = &quot;Conversion Rate (%)&quot;,
    fill = &quot;Group&quot;
  ) +
  theme_bw()</code></pre>
<p><img src="p01_files/figure-html/visualize-conversion-rate-1.png" alt="" width="672" /></p>
<p>Now that we know what percentage of users paid in each group, this
doesn’t really tell us the full story. We only know that slightly more
people paid in group ‘a’ But we would also want to know how much these
paying users are spending.</p>
</div>
<div id="average-revenue-per-user-arpu" class="section level3">
<h3>Average Revenue Per User (ARPU)</h3>
<p>I will calculate the average revenue spent per user (total revenue in
group/total number of users in group).We are now incorporating th
conversion rates with their level of spending.</p>
<pre class="r"><code>ARPU_by_group &lt;- ab %&gt;% 
  group_by(testgroup) %&gt;%
  summarise(
    ARPU = mean(revenue),   #calculate the mean of revenue now (instead of paying user)
    n_users = n ()
  )</code></pre>
<pre class="r"><code>ggplot(ARPU_by_group,
       aes(x = testgroup,
           y = ARPU, 
           fill = testgroup)) + 
  geom_col() + 
  scale_fill_manual(values = c(&quot;a&quot; = &quot;firebrick&quot;,
                               &quot;b&quot; = &quot;forestgreen&quot;)) +
  labs (
    title = &quot;Average Revenue Per User by Test Group&quot;,
    x = &quot;Test Group&quot;,
    y = &quot;ARPU ($)&quot;,
    fill = &quot;Group&quot;
  ) +
  theme_bw()</code></pre>
<p><img src="p01_files/figure-html/visualize_ARPU-1.png" alt="" width="672" /></p>
<p>This is a bit interesting. Earlier the conversion rate calculation
showed us that Group A has slightly more number of users that are
paying. But, now we see that in Group B, there is slightly more money
spent per user overall. This suggests that although slightly fewer users
are making purchases in Group B, those who do may be spending more on
average compared to Group A. It’s important to note that the outliers
may be affecting our data though since our revenue distribution is
really skewed.</p>
</div>
<div id="revenue-distribution-by-group" class="section level3">
<h3>Revenue Distribution by Group</h3>
<pre class="r"><code>ggplot(ab, aes(x = revenue, fill = testgroup)) +
  geom_histogram() +
facet_wrap(~testgroup) +
  labs(
    title = &quot;Revenue Distribution by Test Group&quot;,
    x = &quot;Revenue ($)&quot;,
    y = &quot;Number of Users&quot;
  ) +
  theme_bw() +
  theme(legend.position = &quot;none&quot;)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
<p><img src="p01_files/figure-html/revenue-histogram-by-group-1.png" alt="" width="672" /></p>
<p>Let’s look at the spending patterns in the two groups, among those
who paid.</p>
<pre class="r"><code>ab %&gt;%
  filter(revenue &gt; 0) %&gt;%
  ggplot(aes(x = revenue, fill = testgroup)) +
  geom_histogram() +
  facet_wrap(~testgroup) +
  labs(
    title = &quot;Revenue Distribution Among Paying Users&quot;,
    x = &quot;Revenue ($)&quot;,
    y = &quot;Number of Paying Users&quot;
  ) +
  theme_bw() +
  theme(legend.position = &quot;none&quot;)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
<p><img src="p01_files/figure-html/histogram-among-payers-only-1.png" alt="" width="672" /></p>
</div>
<div id="hypothesis-testing-for-conversion-rates"
class="section level3">
<h3>Hypothesis Testing for Conversion Rates</h3>
<p>Now that we have seen some of the comparison metrics, let us test if
the difference between the two groups is significant. We will use
proportion testing since we are comparing proportions.</p>
<pre class="r"><code>conv_table &lt;- ab %&gt;%
  group_by(testgroup) %&gt;%
  summarise(
    payers = sum(payer_user), #how many users paid
    total = n() #how many uusers in each group
  )</code></pre>
<pre class="r"><code>prop_result &lt;- prop.test(x = conv_table$payers, n = conv_table$total)
prop_result</code></pre>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  conv_table$payers out of conv_table$total
## X-squared = 4.3747, df = 1, p-value = 0.03648
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  3.952707e-05 1.227383e-03
## sample estimates:
##      prop 1      prop 2 
## 0.009539690 0.008906235</code></pre>
<p>From the analysis, we can see that a sample test for equality of
proportions shows that the conversion rate for Group A (~0.95%) was
significantly higher than in group B (~0.89%), χ²(1) = 4.37, p = .036.
However, the magnitude of the effect is still very small (only about
0.06% difference).</p>
</div>
<div id="hypothesis-testing-for-arpu" class="section level3">
<h3>Hypothesis Testing for ARPU</h3>
<pre class="r"><code>arpu_test &lt;- t.test(revenue ~ testgroup, data = ab)

arpu_test</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  revenue by testgroup
## t = -0.62349, df = 240991, p-value = 0.533
## alternative hypothesis: true difference in means between group a and group b is not equal to 0
## 95 percent confidence interval:
##  -5.542295  2.867161
## sample estimates:
## mean in group a mean in group b 
##        25.41372        26.75129</code></pre>
<p>We can see that a Welch two-sample t-test indicates that the
difference in average revenue per user between group A (M = 25.41) and
group B (M = 26.75) was not statistically significant, t(240,991) =
-0.62, p = .533. Eventhough group B exhibited a slightly higher mean
revenue, the difference was small relative to overall variability in
spending.</p>
</div>
<div id="conclusion" class="section level3">
<h3>Conclusion</h3>
<p>The Kaggle challenge was to decide which offer set performs best by
determining the appropriate metrics for a robust evaluation.</p>
<p>Here, we tested two promotional offer designs across approximately
400,000 users. Group A resulted in a slighlty higher percentage of
paying users (0.95% vs 0.89%). While the difference was statistically
significant (perhaps due to the large size), the absolute difference
between the two groups was only 0.06%. In terms of revenue generated per
user, Group B generated slightly higher average revenue ($26.75 vs
$25.41), but this difference wasn’t found to be statistically
significant. Overall, I would argue that there is no strong evidence
that either offer meaningfully outperforms the other in revenue
impact.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
