<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Portfolio 10: Creating Figures From Eye-Tracking Data for Poster Presentation</title>

<script src="site_libs/header-attrs-2.31/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
<li>
  <a href="p10.html">Portfolio 10</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Portfolio 10: Creating Figures From
Eye-Tracking Data for Poster Presentation</h1>

</div>


<blockquote>
<p>Goal For this portfolio piece, I wanted to practice creating figures
that I want to use for my first year poster presentation. In the
previous portfolio piece, I focused on understanding the eye-tracking
dataset, creating a cleaner trial-level and fixation-level dataset, and
looking at what the data is looking like. For this piece, I wanted to
build on that understanding to make more polished visualizations that
summarize the main patterns in the data.</p>
</blockquote>
<p>Here are the figures I want to show in my poster:</p>
<ol style="list-style-type: decimal">
<li><strong>Response time cost by block</strong>: Were participants
slower when a singleton distractor was present?</li>
<li><strong>Oculomotor capture by block</strong>: How often did the
first fixation land on the singleton distractor?</li>
<li><strong>Dwell time by block</strong>: When participants looked at
the singleton, how long did they stay on it?</li>
</ol>
<p>These figures are useful because they show change over time. The
broader research question is whether participants learned to avoid or
disengage from distracting singleton colors across blocks.</p>
<div id="load-packages" class="section level2">
<h2>Load Packages</h2>
<pre class="r"><code>library(tidyverse)
library(janitor)
library(scales)
library(broom)</code></pre>
</div>
<div id="read-the-data" class="section level2">
<h2>Read the Data</h2>
<pre class="r"><code>fix_raw &lt;- read_tsv(&quot;data/fix_report.txt&quot;, na = c(&quot;.&quot;, &quot;NA&quot;), show_col_types = FALSE) %&gt;%
  clean_names() %&gt;%
  rename_with(~ str_remove(.x, &quot;^t_&quot;))

glimpse(fix_raw)</code></pre>
<pre><code>## Rows: 65,876
## Columns: 29
## $ subjnum                 &lt;dbl&gt; 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3…
## $ block                   &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ trial                   &lt;dbl&gt; 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5…
## $ acc                     &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ rt                      &lt;dbl&gt; 1521, 1521, 1521, 1521, 1521, 997, 997, 997, 9…
## $ sing_pres               &lt;chr&gt; &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;…
## $ targ_loc                &lt;dbl&gt; 3, 3, 3, 3, 3, 7, 7, 7, 7, 8, 8, 8, 8, 1, 1, 1…
## $ sing_loc                &lt;dbl&gt; 7, 7, 7, 7, 7, 8, 8, 8, 8, 4, 4, 4, 4, 4, 4, 4…
## $ previous_sac_start_time &lt;dbl&gt; NA, 23, 273, 525, 783, NA, 158, 224, 392, NA, …
## $ current_fix_x           &lt;dbl&gt; 953.8, 947.9, 1056.3, 1403.0, 1375.1, 971.0, 7…
## $ current_fix_y           &lt;dbl&gt; 460.9, 487.8, 76.8, 441.9, 484.6, 485.4, 394.9…
## $ current_fix_index       &lt;dbl&gt; 1, 2, 3, 4, 5, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3…
## $ current_fix_duration    &lt;dbl&gt; 23, 232, 128, 198, 722, 158, 26, 126, 554, 274…
## $ current_fix_end         &lt;dbl&gt; 21, 271, 523, 781, 1519, 156, 222, 390, 962, 2…
## $ previous_sac_end_time   &lt;dbl&gt; NA, 39, 395, 583, 797, NA, 196, 264, 408, NA, …
## $ targ_shape              &lt;chr&gt; &quot;circle&quot;, &quot;circle&quot;, &quot;circle&quot;, &quot;circle&quot;, &quot;circl…
## $ targ_id                 &lt;chr&gt; &quot;H&quot;, &quot;H&quot;, &quot;H&quot;, &quot;H&quot;, &quot;H&quot;, &quot;V&quot;, &quot;V&quot;, &quot;V&quot;, &quot;V&quot;, &quot;…
## $ sing_col                &lt;chr&gt; &quot;green&quot;, &quot;green&quot;, &quot;green&quot;, &quot;green&quot;, &quot;green&quot;, &quot;…
## $ resp                    &lt;chr&gt; &quot;H&quot;, &quot;H&quot;, &quot;H&quot;, &quot;H&quot;, &quot;H&quot;, &quot;V&quot;, &quot;V&quot;, &quot;V&quot;, &quot;V&quot;, &quot;…
## $ age                     &lt;dbl&gt; 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18…
## $ exp_vers                &lt;dbl&gt; 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3…
## $ gender                  &lt;chr&gt; &quot;F&quot;, &quot;F&quot;, &quot;F&quot;, &quot;F&quot;, &quot;F&quot;, &quot;F&quot;, &quot;F&quot;, &quot;F&quot;, &quot;F&quot;, &quot;…
## $ hand                    &lt;chr&gt; &quot;L&quot;, &quot;L&quot;, &quot;L&quot;, &quot;L&quot;, &quot;L&quot;, &quot;L&quot;, &quot;L&quot;, &quot;L&quot;, &quot;L&quot;, &quot;…
## $ recording_session_label &lt;chr&gt; &quot;SS_3&quot;, &quot;SS_3&quot;, &quot;SS_3&quot;, &quot;SS_3&quot;, &quot;SS_3&quot;, &quot;SS_3&quot;…
## $ condition               &lt;chr&gt; &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;…
## $ phase                   &lt;chr&gt; &quot;practice&quot;, &quot;practice&quot;, &quot;practice&quot;, &quot;practice&quot;…
## $ sing_prob               &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ previous_fix_end        &lt;dbl&gt; NA, 21, 271, 523, 781, NA, 156, 222, 390, NA, …
## $ current_fix_start       &lt;dbl&gt; 0, 41, 397, 585, 799, 0, 198, 266, 410, 0, 318…</code></pre>
<div id="cleaning-and-relabeling" class="section level3">
<h3>Cleaning and Relabeling</h3>
<p>The original dataset is fixation-level, meaning a single trial can
appear on multiple rows if the participant made multiple fixations. We
once again convert key variables to numeric, remove practice trials,
create readable singleton-condition labels, and keep only the
experimental phase.</p>
<pre class="r"><code>fix_clean &lt;- fix_raw %&gt;%
  mutate(
    subjnum = as.numeric(subjnum),
    block = as.numeric(block),
    block_norm = block - 1,
    trial = as.numeric(trial),
    acc = as.numeric(acc),
    rt = as.numeric(rt),
    dwell = as.numeric(current_fix_duration),
    targ_loc = as.numeric(targ_loc),
    sing_loc = as.numeric(sing_loc),
    current_fix_x = as.numeric(current_fix_x),
    current_fix_y = as.numeric(current_fix_y),
    current_fix_index = as.numeric(current_fix_index),
    current_fix_start = as.numeric(current_fix_start),
    sing_prob = case_when(
      sing_pres == &quot;A&quot; ~ &quot;Absent&quot;,
      sing_prob == &quot;high&quot; ~ &quot;High&quot;,
      sing_prob == &quot;low&quot; ~ &quot;Low&quot;,
      TRUE ~ as.character(sing_prob)
    ),
    sing_loc = if_else(sing_pres == &quot;A&quot;, 0, sing_loc),
    keep_rt = rt &gt; 200 &amp; rt &lt;= 2500
  ) %&gt;%
  filter(
    phase == &quot;experiment&quot;,
    block_norm &gt;= 1,
    block_norm &lt;= 14,
    !is.na(subjnum),
    !is.na(trial),
    !is.na(sing_prob)
  )</code></pre>
</div>
<div id="helper-function-for-plot-summaries" class="section level3">
<h3>Helper Function for Plot Summaries</h3>
<p>For the poster figures, I want one mean value per condition and
block. We are using helper function that calculates the mean and
standard error.</p>
<pre class="r"><code>summary_se &lt;- function(data, value_col, group_cols) {
  data %&gt;%
    group_by(across(all_of(group_cols))) %&gt;%
    summarise(
      mean = mean({{ value_col }}, na.rm = TRUE),
      sd = sd({{ value_col }}, na.rm = TRUE),
      n = n(),
      se = sd / sqrt(n),
      lower = mean - se,
      upper = mean + se,
      .groups = &quot;drop&quot;
    )
}</code></pre>
</div>
</div>
<div id="figure-theme" class="section level2">
<h2>Figure Theme</h2>
<p>I used one consistent theme across all the figures so that they look
like they belong together.</p>
<pre class="r"><code>poster_theme &lt;- theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = &quot;bold&quot;, size = 16),
    plot.subtitle = element_text(size = 11),
    legend.position = &quot;top&quot;,
    legend.title = element_blank(),
    panel.grid.minor = element_blank()
  )

condition_colors &lt;- c(
  &quot;High&quot; = &quot;#1F9EB7&quot;,
  &quot;Low&quot; = &quot;#F4B400&quot;,
  &quot;Absent&quot; = &quot;#8ECAE6&quot;
)</code></pre>
</div>
<div id="figure-1-response-time-cost-by-block" class="section level1">
<h1>Figure 1: Response Time Cost by Block</h1>
<div id="why-this-figure" class="section level2">
<h2>Why This Figure?</h2>
<p>Response time cost compares singleton-present trials to
singleton-absent trials. If participants are slower when the singleton
is present, that suggests the distractor made the task harder. I
calculated this separately for high-frequency and low-frequency
singleton trials.</p>
<p>For each participant and block, I calculated:</p>
<ul>
<li><strong>High RT cost</strong> = High singleton RT - Absent RT</li>
<li><strong>Low RT cost</strong> = Low singleton RT - Absent RT</li>
</ul>
<pre class="r"><code>trial_data &lt;- fix_clean %&gt;%
  distinct(subjnum, trial, .keep_all = TRUE) %&gt;%
  filter(
    keep_rt,
    acc == 1,
    !is.na(rt),
    !is.na(sing_prob)
  )

rt_by_subject_block &lt;- trial_data %&gt;%
  group_by(subjnum, block_norm, sing_prob) %&gt;%
  summarise(mean_rt = mean(rt, na.rm = TRUE), .groups = &quot;drop&quot;) %&gt;%
  pivot_wider(names_from = sing_prob, values_from = mean_rt) %&gt;%
  filter(!is.na(Absent)) %&gt;%
  mutate(
    High = High - Absent,
    Low = Low - Absent
  ) %&gt;%
  select(subjnum, block_norm, High, Low) %&gt;%
  pivot_longer(
    cols = c(High, Low),
    names_to = &quot;singleton_frequency&quot;,
    values_to = &quot;rt_cost&quot;
  ) %&gt;%
  filter(!is.na(rt_cost))

rt_cost_summary &lt;- summary_se(
  data = rt_by_subject_block,
  value_col = rt_cost,
  group_cols = c(&quot;block_norm&quot;, &quot;singleton_frequency&quot;)
)

rt_cost_summary</code></pre>
<pre><code>## # A tibble: 28 × 8
##    block_norm singleton_frequency  mean    sd     n    se lower upper
##         &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1          1 High                 179.  131.    32  23.2 156.   202.
##  2          1 Low                  217.  169.    32  29.8 187.   247.
##  3          2 High                 148.  140.    32  24.7 123.   172.
##  4          2 Low                  196.  223.    31  40.0 156.   236.
##  5          3 High                 121.  137.    32  24.2  96.5  145.
##  6          3 Low                  174.  194.    32  34.3 140.   208.
##  7          4 High                 176.  106.    32  18.7 157.   195.
##  8          4 Low                  196.  155.    32  27.4 169.   223.
##  9          5 High                 140.  135.    32  23.9 116.   164.
## 10          5 Low                  185.  193.    32  34.1 151.   219.
## # ℹ 18 more rows</code></pre>
<pre class="r"><code>ggplot(rt_cost_summary, aes(
  x = block_norm,
  y = mean,
  color = singleton_frequency,
  fill = singleton_frequency
)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.18, color = NA) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 2.8) +
  geom_hline(yintercept = 0, linetype = &quot;dashed&quot;, color = &quot;gray40&quot;) +
  scale_color_manual(values = condition_colors) +
  scale_fill_manual(values = condition_colors) +
  scale_x_continuous(breaks = 1:14) +
  labs(
    title = &quot;Singleton Presence Cost Across Blocks&quot;,
    subtitle = &quot;Response time cost = singleton-present RT minus singleton-absent RT&quot;,
    x = &quot;Block&quot;,
    y = &quot;RT cost (ms)&quot;
  ) +
  poster_theme</code></pre>
<p><img src="p10_files/figure-html/rt-cost-plot-1.png" alt="" width="864" /></p>
</div>
<div id="interpretation" class="section level2">
<h2>Interpretation</h2>
<p>This figure shows whether singleton-present trials were slower than
singleton-absent trials. Values above zero mean participants were slower
when the singleton was present. As we can see the lines decrease across
blocks, which would suggest participants became less distracted over
time.</p>
</div>
</div>
<div id="classifying-fixations-for-eye-tracking-figures"
class="section level1">
<h1>Classifying Fixations for Eye-Tracking Figures</h1>
<p>The next two figures require knowing whether a fixation landed on the
target, singleton, or a nonsingleton item. The raw data contain fixation
coordinates, but not a simple label for the item being fixated. So, we
approximate the item by comparing each fixation coordinate to the eight
possible item locations.</p>
<pre class="r"><code>screen_width &lt;- 1920
screen_height &lt;- 1080
center_x &lt;- screen_width / 2
center_y &lt;- screen_height / 2
eccentricity &lt;- 400
fix_zone &lt;- 90
set_size &lt;- 8

item_locations &lt;- tibble(
  item_loc = 1:set_size,
  angle = (item_loc - 1) * 2 * pi / set_size,
  item_x = center_x + eccentricity * sin(angle),
  item_y = center_y - eccentricity * cos(angle)
)

fix_items &lt;- fix_clean %&gt;%
  filter(
    keep_rt,
    acc == 1,
    !is.na(current_fix_x),
    !is.na(current_fix_y),
    !is.na(dwell)
  ) %&gt;%
  mutate(row_id = row_number()) %&gt;%
  crossing(item_locations) %&gt;%
  mutate(distance = sqrt((current_fix_x - item_x)^2 + (current_fix_y - item_y)^2)) %&gt;%
  group_by(row_id) %&gt;%
  slice_min(distance, n = 1, with_ties = FALSE) %&gt;%
  ungroup() %&gt;%
  mutate(
    curr_loc = if_else(distance &lt;= fix_zone, item_loc, NA_integer_),
    curr_item = case_when(
      is.na(curr_loc) ~ NA_character_,
      curr_loc == targ_loc ~ &quot;Target&quot;,
      curr_loc == sing_loc ~ &quot;Singleton&quot;,
      TRUE ~ &quot;Nonsingleton&quot;
    )
  )</code></pre>
</div>
<div id="figure-2-oculomotor-capture-by-block" class="section level1">
<h1>Figure 2: Oculomotor Capture by Block</h1>
<div id="why-this-figure-1" class="section level2">
<h2>Why This Figure?</h2>
<p>Oculomotor capture asks whether the eyes were pulled to the singleton
distractor. For this figure, I looked at the first fixation that landed
on a display item on each trial. Then I calculated the percentage of
trials where that first fixation landed on the singleton.</p>
<pre class="r"><code>first_display_fix &lt;- fix_items %&gt;%
  filter(
    sing_prob %in% c(&quot;High&quot;, &quot;Low&quot;),
    !is.na(curr_item)
  ) %&gt;%
  group_by(subjnum, trial) %&gt;%
  arrange(current_fix_start, current_fix_index, .by_group = TRUE) %&gt;%
  slice(1) %&gt;%
  ungroup() %&gt;%
  mutate(first_on_singleton = curr_item == &quot;Singleton&quot;)

oculomotor_by_subject_block &lt;- first_display_fix %&gt;%
  group_by(subjnum, block_norm, sing_prob) %&gt;%
  summarise(
    oculomotor_capture = mean(first_on_singleton, na.rm = TRUE) * 100,
    .groups = &quot;drop&quot;
  )

oculomotor_summary &lt;- summary_se(
  data = oculomotor_by_subject_block,
  value_col = oculomotor_capture,
  group_cols = c(&quot;block_norm&quot;, &quot;sing_prob&quot;)
)

oculomotor_summary</code></pre>
<pre><code>## # A tibble: 28 × 8
##    block_norm sing_prob  mean    sd     n    se lower upper
##         &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1          1 High       56.1  25.3    32  4.48  51.6  60.6
##  2          1 Low        59.9  31.5    32  5.57  54.3  65.5
##  3          2 High       47.2  21.6    32  3.81  43.4  51.1
##  4          2 Low        47.8  28.3    31  5.08  42.8  52.9
##  5          3 High       38.3  17.3    32  3.05  35.3  41.4
##  6          3 Low        45.3  32.4    32  5.72  39.6  51.0
##  7          4 High       37.8  22.7    32  4.01  33.8  41.8
##  8          4 Low        44.8  30.6    32  5.41  39.4  50.2
##  9          5 High       32.1  21.7    32  3.84  28.2  35.9
## 10          5 Low        48.2  27.7    32  4.90  43.3  53.1
## # ℹ 18 more rows</code></pre>
<pre class="r"><code>ggplot(oculomotor_summary, aes(
  x = block_norm,
  y = mean,
  color = sing_prob,
  fill = sing_prob
)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.18, color = NA) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 2.8) +
  scale_color_manual(values = condition_colors) +
  scale_fill_manual(values = condition_colors) +
  scale_x_continuous(breaks = 1:14) +
  scale_y_continuous(labels = label_percent(scale = 1)) +
  labs(
    title = &quot;Oculomotor Capture Across Blocks&quot;,
    subtitle = &quot;Percent of first display fixations landing on the singleton&quot;,
    x = &quot;Block&quot;,
    y = &quot;First fixations on singleton&quot;
  ) +
  poster_theme</code></pre>
<p><img src="p10_files/figure-html/oculomotor-capture-plot-1.png" alt="" width="864" /></p>
<p>This plot shows how often participants first looked at the singleton
distractor. A decrease across blocks suggest that participants became
better at avoiding the singleton. This is related to the idea of
oculomotor suppression.</p>
</div>
</div>
<div id="figure-3-first-singleton-fixation-dwell-time-by-block"
class="section level1">
<h1>Figure 3: First Singleton Fixation Dwell Time by Block</h1>
<div id="why-this-figure-2" class="section level2">
<h2>Why This Figure?</h2>
<p>The previous figure asks whether the singleton captured the eyes.
This figure asks what happened after the singleton was fixated. Dwell
time measures how long participants stayed on the singleton once they
looked at it. Shorter dwell times suggest faster disengagement.</p>
<pre class="r"><code>first_singleton_fix &lt;- fix_items %&gt;%
  filter(
    sing_prob %in% c(&quot;High&quot;, &quot;Low&quot;),
    curr_item == &quot;Singleton&quot;,
    !is.na(dwell)
  ) %&gt;%
  group_by(subjnum, trial) %&gt;%
  arrange(current_fix_start, current_fix_index, .by_group = TRUE) %&gt;%
  slice(1) %&gt;%
  ungroup()

dwell_by_subject_block &lt;- first_singleton_fix %&gt;%
  group_by(subjnum, block_norm, sing_prob) %&gt;%
  summarise(
    dwell_time = mean(dwell, na.rm = TRUE),
    .groups = &quot;drop&quot;
  )

dwell_summary &lt;- summary_se(
  data = dwell_by_subject_block,
  value_col = dwell_time,
  group_cols = c(&quot;block_norm&quot;, &quot;sing_prob&quot;)
)

dwell_summary</code></pre>
<pre><code>## # A tibble: 28 × 8
##    block_norm sing_prob  mean    sd     n    se lower upper
##         &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1          1 High       190.  57.1    32 10.1   180.  200.
##  2          1 Low        214.  90.5    30 16.5   197.  230.
##  3          2 High       164.  46.7    31  8.38  156.  172.
##  4          2 Low        165.  43.0    29  7.98  157.  173.
##  5          3 High       167.  45.9    31  8.25  158.  175.
##  6          3 Low        172.  69.2    28 13.1   159.  185.
##  7          4 High       171.  41.8    30  7.63  164.  179.
##  8          4 Low        176.  80.1    24 16.4   160.  192.
##  9          5 High       155.  45.1    29  8.38  147.  164.
## 10          5 Low        156.  34.5    27  6.65  150.  163.
## # ℹ 18 more rows</code></pre>
<pre class="r"><code>ggplot(dwell_summary, aes(
  x = block_norm,
  y = mean,
  color = sing_prob,
  fill = sing_prob
)) +
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.18, color = NA) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 2.8) +
  scale_color_manual(values = condition_colors) +
  scale_fill_manual(values = condition_colors) +
  scale_x_continuous(breaks = 1:14) +
  labs(
    title = &quot;First Singleton Fixation Dwell Time Across Blocks&quot;,
    subtitle = &quot;Mean duration of the first fixation on the singleton&quot;,
    x = &quot;Block&quot;,
    y = &quot;Dwell time (ms)&quot;
  ) +
  poster_theme</code></pre>
<p><img src="p10_files/figure-html/dwell-block-plot-1.png" alt="" width="864" /></p>
<p>This plot shows how long participants stayed on the singleton after
looking at it. As we can see, dwell time decreases across blocks, which
suggests that participants may be learning to disengage from the
singleton more quickly. This is related to the idea ofrapid
disengagement.</p>
<p>This figure complements the oculomotor capture plot: one figure shows
whether participants looked at the singleton, while the other shows how
long they stayed there.</p>
<div id="exploratory-slope-analysis" class="section level3">
<h3>Exploratory Slope Analysis</h3>
<p>When I presented these figures, one question I received was whether I
had tested the slope of the lines across blocks. The graphs visually
suggest that oculomotor capture and dwell time may decrease over time,
but a regression can help quantify whether the trend is negative.</p>
<p>So I wanted to add practicing that to this piece as well. These
models estimate whether each outcome changes as block number increases.
I am treating these as practice models for connecting visualizations to
numerical summaries, not as the final statistical analysis for the
research project.</p>
</div>
</div>
<div id="oculomotor-capture-slopes" class="section level2">
<h2>Oculomotor Capture Slopes</h2>
<pre class="r"><code>oculomotor_slopes &lt;- oculomotor_by_subject_block %&gt;%
  group_by(sing_prob) %&gt;%
  nest() %&gt;%
  mutate(
    model = purrr::map(data, ~ lm(oculomotor_capture ~ block_norm, data = .x)),
    results = purrr::map(model, broom::tidy)
  ) %&gt;%
  select(sing_prob, results) %&gt;%
  unnest(results) %&gt;%
  filter(term == &quot;block_norm&quot;) %&gt;%
  select(
    singleton_condition = sing_prob,
    slope = estimate,
    std_error = std.error,
    statistic,
    p_value = p.value
  )

oculomotor_slopes</code></pre>
<pre><code>## # A tibble: 2 × 5
## # Groups:   singleton_condition [2]
##   singleton_condition slope std_error statistic  p_value
##   &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 High                -1.90     0.255     -7.46 4.44e-13
## 2 Low                 -1.60     0.359     -4.46 1.04e- 5</code></pre>
<p>This model estimates the change in oculomotor capture for each
additional block. The slope analysis showed that oculomotor capture
decreased across blocks for both singleton conditions.</p>
<p>In the high-frequency condition, the slope was about -1.90, meaning
that first fixations on the singleton decreased by about 1.9 percentage
points per block. In the low-frequency condition, the slope was about
-1.60, meaning that first fixations on the singleton decreased by about
1.6 percentage points per block.</p>
<p>Both slopes were negative, which supports the visual pattern in the
graph: participants became less likely to look first at the singleton as
the experiment progressed. This is consistent with the idea that
participants learned to avoid looking at the singleton over time.</p>
<p>The p-values were very small for both conditions, suggesting that the
negative slopes were unlikely to be due to random noise in this
exploratory model.</p>
</div>
<div id="dwell-time-slopes" class="section level2">
<h2>Dwell Time Slopes</h2>
<pre class="r"><code>dwell_slopes &lt;- dwell_by_subject_block %&gt;%
  group_by(sing_prob) %&gt;%
  nest() %&gt;%
  mutate(
    model = purrr::map(data, ~ lm(dwell_time ~ block_norm, data = .x)),
    results = purrr::map(model, broom::tidy)
  ) %&gt;%
  select(sing_prob, results) %&gt;%
  unnest(results) %&gt;%
  filter(term == &quot;block_norm&quot;) %&gt;%
  select(
    singleton_condition = sing_prob,
    slope = estimate,
    std_error = std.error,
    statistic,
    p_value = p.value
  )

dwell_slopes</code></pre>
<pre><code>## # A tibble: 2 × 5
## # Groups:   singleton_condition [2]
##   singleton_condition slope std_error statistic     p_value
##   &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1 High                -2.93     0.590     -4.95 0.00000106 
## 2 Low                 -3.91     0.781     -5.00 0.000000887</code></pre>
<p>This model estimates the change in first singleton fixation dwell
time for each additional block. The dwell-time slope analysis showed
that first singleton fixation dwell time also decreased across
blocks.</p>
<p>In the high-frequency condition, dwell time decreased by about 2.9 ms
per block. In the low-frequency condition, dwell time decreased by about
3.9 ms per block.</p>
<p>Again, both slopes were negative, which supports the visual
interpretation that participants disengaged from the singleton more
quickly over time. This pattern is consistent with the rapid
disengagement idea: even when participants looked at the singleton, they
spent less time looking at it as the task progressed. The p-values were
very small for both conditions here as well.</p>
<div id="interaction-models" class="section level3">
<h3>Interaction Models</h3>
<p>After estimating separate slopes for the high- and low-frequency
singleton conditions, I also tested an interaction model. The
interaction model asks whether the change across blocks differs between
the two singleton conditions (high vs low).</p>
</div>
<div id="oculomotor-capture-interaction" class="section level3">
<h3>Oculomotor capture interaction</h3>
<pre class="r"><code>oculomotor_interaction &lt;- lm(
  oculomotor_capture ~ block_norm * sing_prob,
  data = oculomotor_by_subject_block
)


broom::tidy(oculomotor_interaction)</code></pre>
<pre><code>## # A tibble: 4 × 5
##   term                    estimate std.error statistic  p.value
##   &lt;chr&gt;                      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)               47.6       2.64     18.0   3.23e-62
## 2 block_norm                -1.90      0.310    -6.13  1.35e- 9
## 3 sing_probLow               5.35      3.74      1.43  1.53e- 1
## 4 block_norm:sing_probLow    0.300     0.440     0.682 4.96e- 1</code></pre>
<p>The interaction model showed a significant negative block effect for
oculomotor capture.</p>
<p>In the high-frequency singleton condition, oculomotor capture
decreased by about 1.90 percentage points per block. This means that
participants were less likely to make their first fixation on the
singleton as the experiment progressed.</p>
<p>The interaction term for the low-frequency condition was not
significant. This means that the low-frequency slope was not
statistically different from the high-frequency slope in this simplified
model. The estimated low-frequency slope was also negative, about -1.60
percentage points per block.</p>
<p>Overall, this suggests that both high- and low-frequency singleton
conditions showed decreasing oculomotor capture over time. The important
conclusion is that participants looked at the singleton less often
across blocks, but this simplified model did not show strong evidence
that the decrease was different between the high- and low-frequency
conditions.</p>
</div>
<div id="dwell-time-interaction-model" class="section level3">
<h3>Dwell Time Interaction Model</h3>
<pre class="r"><code>dwell_interaction &lt;- lm(
  dwell_time ~ block_norm * sing_prob,
  data = dwell_by_subject_block
)

broom::tidy(dwell_interaction)</code></pre>
<pre><code>## # A tibble: 4 × 5
##   term                    estimate std.error statistic   p.value
##   &lt;chr&gt;                      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)              177.        5.54      31.9  2.13e-142
## 2 block_norm                -2.93      0.664     -4.40 1.21e-  5
## 3 sing_probLow              12.0       8.03       1.49 1.36e-  1
## 4 block_norm:sing_probLow   -0.981     0.965     -1.02 3.10e-  1</code></pre>
<p>The dwell time interaction model showed that first singleton fixation
dwell time decreased across blocks. This suggests that participants
became faster at disengaging from the singleton over time.</p>
<p>However, the interaction term was not significant, meaning the
decrease was not clearly different between the high- and low-frequency
conditions.</p>
<p>Overall for the final poster, these figures and analyses are very
helpful in communicating two related hypotheses/ideas of our project.
First, participants may learn to avoid looking at the singleton over
time. Second, when they do look at the singleton, they may learn to
disengage from it more quickly. Together, these patterns help visualize
the learned oculomotor avoidance (combinayion of the two).</p>
</div>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
